# appveyor
version: "{build}"

platform:
  - x64

# Fix line endings on Windows
init:
  - git config --global core.autocrlf input

environment:
  node_version: "8.12.0"
  GH_TOKEN:
    secure: lbTBOM5qMTqpAAp/tMEHULcIpDNLAC+pGV3hIvBZdj0BUQdCrVmrD1kY+j05e42/

matrix:
  fast_finish: true

cache:
  - node_modules -> package.json
  - node_modules -> yarn.lock
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node $env:node_version
  - yarn install
  # - yarn add electron-builder@next --dev # force install next version to test electron-builder

artifacts:
  - path: dist\*

# "test pipe"
test_script:
  - node --version
  - yarn --version
  - yarn
  - yarn coverage
  - yarn make:install

# deploy:
#   - provider: GitHub
#     auth_token:
#       secure: NsZdgUavKmZtXwuqiYcA8DdCNLeHnnExSLZnU7JSGBWosxYu7OrLOlegu8rZUBnV
#     artifact: dist\*
#     draft: true
#     prerelease: false
#     on:
#       appveyor_repo_tag: true

build: off
